export { Hero } from './Hero'
export { StudentNoticeSection } from './StudentNoticeSection'
export { WhatIOfferSection } from './WhatIOfferSection'
export { HowToUseSection } from './HowToUseSection'
export { StatsSection } from './StatsSection'
export { AboutSection } from './AboutSection'
export { TestimonialsSection } from './TestimonialsSection'
export { CtaSection } from './CtaSection'
